# site
title: camille bayas
baseurl:
url: "http://camillebayas.github.io"
favicon:
g_analytics:

# bio
header: camille bayas
desc: >
  Hi! My name is Camille. I am based in Palo Alto, CA. I recently completed my PhD in physical chemistry at Stanford with W. E. Moerner.

# posts
date_format: "%Y"
post_title: Story
post_date: Year
post_cat: Genre

# post detail
prev-next: true

# build settings
markdown: kramdown
# theme: louie
exclude:
  - Gemfile
  - Gemfile.lock
