# site
title: camille bayas
baseurl:
url: "http://camillebayas.github.io"
favicon:
g_analytics:

# bio
header: Camille Bayas
desc: >
  Hi! My name is Camille. I am based in Boston, MA, and I work as a data scientist at <a href="https://www.indigoag.com/">Indigo</a>. I completed my PhD in physical chemistry at Stanford with <a href = "https://web.stanford.edu/group/moerner/">W. E. Moerner</a>.
  
  I enjoy using my statistical and machine learning, coding, and communication skills to guide data-driven decision-making. I love solving complex problems with cross-functional teams.
  
  In my personal time, I enjoy learning new languages (j’apprends le français!) and baking sourdough.

# posts
date_format: "%Y"
post_title: Story
post_date: Year
post_cat: Genre

# post detail
prev-next: true

# build settings
markdown: kramdown
# theme: louie
exclude:
  - Gemfile
  - Gemfile.lock
